PROGRAM=esp_wisleep

EXTRA_COMPONENTS=extras/stdin_uart_interrupt extras/dhcpserver

PROGRAM_ROOT=./..
PROGRAM_SRC_DIR=./..
PROGRAM_SRC_FILES=esp_wisleep.c server.c \
	../umac/umac.c ../uweb/src/uweb.c ../uweb/src/uweb_codec.c

include ../../esp-open-rtos/common.mk
